Rails.application.routes.draw do

  get 'middletown', to: 'middletown#main'
  get 'middletown/partners'
  get 'bedford_ny', to: 'bedford_ny#main'
  get 'bedford_ny/partners'
  get 'warren_nj', to: 'warren_nj#main'
  get 'warren_nj/partners'
  get 'elkridge', to: 'elkridge#main'
  get 'elkridge/partners'
  get 'ellicottcity', to: 'ellicottcity#main'
  get 'ellicottcity/partners'
  get 'chantilly', to: 'chantilly#main'
  get 'chantilly/partners'
  get 'herndon', to: 'herndon#main'
  get 'herndon/partners'
  get 'ashburn', to: 'ashburn#main'
  get 'ashburn/partners'
  get 'arlington', to: 'arlington#main'
  get 'arlington/partners'
  get 'bedfordhills', to: 'bedfordhills#main'
  get 'bedfordhills/partners'
  get 'katonah', to: 'katonah#main'
  get 'katonah/partners'
  get 'poundridge', to: 'poundridge#main'
  get 'poundridge/partners'
  get 'mountkisco', to: 'mountkisco#main'
  get 'mountkisco/partners'
  get 'chappaqua', to: 'chappaqua#main'
  get 'chappaqua/partners'
  get 'briarcliffmanor', to: 'briarcliffmanor#main'
  get 'briarcliffmanor/partners'
  get 'crotononhudson', to: 'crotononhudson#main'
  get 'crotononhudson/partners'
  get 'pleasantville', to: 'pleasantville#main'
  get 'pleasantville/partners'
  get 'harrison', to: 'harrison#main'
  get 'harrison/partners'
  get 'irvington', to: 'irvington#main'
  get 'irvington/partners'
  get 'southborough', to: 'southborough#main'
  get 'southborough/partners'
  get 'marlborough', to: 'marlborough#main'
  get 'marlborough/partners'
  get 'hopkinton', to: 'hopkinton#main'
  get 'hopkinton/partners'
  get 'westborough', to: 'westborough#main'
  get 'westborough/partners'
  get 'northborough', to: 'northborough#main'
  get 'northborough/partners'
  get 'shrewsbury', to: 'shrewsbury#main'
  get 'shrewsbury/partners'
  get 'swampscott', to: 'swampscott#main'
  get 'swampscott/partners'
  get 'marblehead', to: 'marblehead#main'
  get 'marblehead/partners'
  get 'manchesterbythesea', to: 'manchesterbythesea#main'
  get 'manchesterbythesea/partners'
  get 'beverly', to: 'beverly#main'
  get 'beverly/partners'
  get 'salem', to: 'salem#main'
  get 'salem/partners'
  get 'bristol', to: 'bristol#main'
  get 'bristol/partners'
  get 'portsmouth', to: 'portsmouth#main'
  get 'portsmouth/partners'
  get 'milton', to: 'milton#main'
  get 'milton/partners'
  get 'dedham', to: 'dedham#main'
  get 'dedham/partners'
  get 'norwood', to: 'norwood#main'
  get 'norwood/partners'
  get 'rockyhill', to: 'rockyhill#main'
  get 'rockyhill/partners'
  get 'eastwindsor', to: 'eastwindsor#main'
  get 'eastwindsor/partners'
  get 'princetonjunction', to: 'princetonjunction#main'
  get 'princetonjunction/partners'
  get 'lawrenceville', to: 'lawrenceville#main'
  get 'lawrenceville/partners'
  get 'princeton', to: 'princeton#main'
  get 'princeton/partners'
  get 'rivervale', to: 'rivervale#main'
  get 'rivervale/partners'
  get 'montville', to: 'montville#main'
  get 'montville/partners'
  get 'wayne_nj', to: '', to: 'wayne_nj#main'
  get 'wayne_nj/partners'
  get 'westwood_nj', to: 'westwood_nj#main'
  get 'westwood_nj/partners'

  get 'referrals', to: 'homedelivery_referals#index'
  resources :homedelivery_referals

  namespace :api do
    namespace :v1 do
      get 'ordheads/api'
      resources :ordheads
    end
  end

  get 'andytote', to: 'andytote#main'
  get 'andytote/selected'
  get 'routetote', to: 'routetote#main'
  get 'tote', to: 'tote#main'
  get 'alpine', to: 'alpine#main'
  get 'alpine/partners'
  get 'barrington', to: 'barrington#main'
  get 'barrington/partners'
  get 'baskingridge', to: 'baskingridge#main'
  get 'baskingridge/partners'
  get 'bayberry', to: 'bayberry#main'
  get 'bayberry/partners'
  get 'bridgewater', to: 'bridgewater#main'
  get 'bridgewater/partners'
  get 'bedford', to: 'bedford#main'
  get 'bedford/partners'
  get 'beechmontwoods', to: 'beechmontwoods#main'
  get 'beechmontwoods/partners'
  get 'berkeleyheights', to: 'berkeleyheights#main'
  get 'berkeleyheights/partners'
  get 'bernardsville', to: 'bernardsville#main'
  get 'bernardsville/partners'
  get 'berwyn', to: 'berwyn#main'
  get 'berwyn/partners'
  get 'bethesda', to: 'bethesda#main'
  get 'bethesda/partners'
  get 'bloomfield', to: 'bloomfield#main'
  get 'bloomfield/partners'
  get 'bronxville', to: 'bronxville#main'
  get 'bronxville/partners'
  get 'boontontownship', to: 'boontontownship#main'
  get 'boontontownship/partners'
  get 'brookeville', to: 'brookeville#main'
  get 'brookeville/partners'
  get 'brynmawr', to: 'brynmawr#main'
  get 'brynmawr/partners'
  get 'caldwell', to: 'caldwell#main'
  get 'caldwell/partners'
  get 'canton', to: 'canton#main'
  get 'canton/partners'
  get 'cedargrove', to: 'cedargrove#main'
  get 'cedargrove/partners'
  get 'chester', to: 'chester#main'
  get 'chester/partners'
  get 'chatham', to: 'chatham#main'
  get 'chatham/partners'
  get 'chevychase', to: 'chevychase#main'
  get 'chevychase/partners'
  get 'clarksville', to: 'clarksville#main'
  get 'clarksville/partners'
  get 'closter', to: 'closter#main'
  get 'closter/partners'
  get 'cohasset', to: 'cohasset#main'
  get 'cohasset/partners'
  get 'columbia', to: 'columbia#main'
  get 'columbia/partners'
  get 'concord', to: 'concord#main'
  get 'concord/partners'
  get 'cranford', to: 'cranford#main'
  get 'cranford/partners'
  get 'cresskill', to: 'cresskill#main'
  get 'cresskill/partners'
  get 'darien', to: 'darien#main'
  get 'darien/partners'
  get 'darnestown', to: 'darnestown#main'
  get 'darnestown/partners'
  get 'denville', to: 'denville#main'
  get 'denville/partners'
  get 'dobbsferry', to: 'dobbsferry#main'
  get 'dobbsferry/partners'
  get 'dover', to: 'dover#main'
  get 'dover/partners'
  get 'duxbury', to: 'duxbury#main'
  get 'duxbury/partners'
  get 'eastgreenwich', to: 'eastgreenwich#main'
  get 'eastgreenwich/partners'
  get 'elmsford', to: 'elmsford#main'
  get 'elmsford/partners'
  get 'englewood', to: 'englewood#main'
  get 'englewood/partners'
  get 'essexfells', to: 'essexfells#main'
  get 'essexfells/partners'
  get 'fallschurch', to: 'fallschurch#main'
  get 'fallschurch/partners'
  get 'fairfax', to: 'fairfax#main'
  get 'fairfax/partners'
  get 'farhills', to: 'farhills#main'
  get 'farhills/partners'
  get 'florhampark', to: 'florhampark#main'
  get 'florhampark/partners'
  get 'franklinlakes', to: 'franklinlakes#main'
  get 'franklinlakes/partners'
  get 'gaithersburg', to: 'gaithersburg#main'
  get 'gaithersburg/partners'
  get 'germantown', to: 'germantown#main'
  get 'germantown/partners'
  get 'glenridge', to: 'glenridge#main'
  get 'glenridge/partners'
  get 'glenrock', to: 'glenrock#main'
  get 'glenrock/partners'
  get 'greatfalls', to: 'greatfalls#main'
  get 'greatfalls/partners'
  get 'greenwich', to: 'greenwich#main'
  get 'greenwich/partners'
  get 'hardingtownship', to: 'hardingtownship#main'
  get 'hardingtownship/partners'
  get 'hastingsonhudson', to: 'hastingsonhudson#main'
  get 'hastingsonhudson/partners'
  get 'haverford', to: 'haverford#main'
  get 'haverford/partners'
  get 'hillsdale', to: 'hillsdale#main'
  get 'hillsdale/partners'
  get 'hingham', to: 'hingham#main'
  get 'hingham/partners'
  get 'hohokus', to: 'hohokus#main'
  get 'hohokus/partners'
  get 'jamestown', to: 'jamestown#main'
  get 'jamestown/partners'
  get 'kensington', to: 'kensington#main'
  get 'kensington/partners'
  get 'larchmont', to: 'larchmont#main'
  get 'larchmont/partners'
  get 'lexington', to: 'lexington#main'
  get 'lexington/partners'
  get 'lincoln', to: 'lincoln#main'
  get 'lincoln/partners'
  get 'livingston', to: 'livingston#main'
  get 'livingston/partners'
  get 'longhilltwp', to: 'longhilltwp#main'
  get 'longhilltwp/partners'
  get 'madison', to: 'madison#main'
  get 'madison/partners'
  get 'mahwah', to: 'mahwah#main'
  get 'mahwah/partners'
  get 'malden', to: 'malden#main'
  get 'malden/partners'
  get 'marshfield', to: 'marshfield#main'
  get 'marshfield/partners'
  get 'melrose', to: 'melrose#main'
  get 'melrose/partners'
  get 'medford', to: 'medford#main'
  get 'medford/partners'
  get 'medway', to: 'medway#main'
  get 'medway/partners'
  get 'mendham', to: 'mendham#main'
  get 'mendham/partners'
  get 'montclair', to: 'montclair#main'
  get 'montclair/partners'
  get 'morrisplains', to: 'morrisplains#main'
  get 'morrisplains/partners'
  get 'morristown', to: 'morristown#main'
  get 'morristown/partners'
  get 'mountainlakes', to: 'mountainlakes#main'
  get 'mountainlakes/partners'
  get 'mountainside', to: 'mountainside#main'
  get 'mountainside/partners'
  get 'natick', to: 'natick#main'
  get 'natick/partners'
  get 'needham', to: 'needham#main'
  get 'needham/partners'
  get 'newcanaan', to: 'newcanaan#main'
  get 'newcanaan/partners'
  get 'newport', to: 'newport#main'
  get 'newport/partners'
  get 'newprovidence', to: 'newprovidence#main'
  get 'newprovidence/partners'
  get 'newton', to: 'newton#main'
  get 'newton/partners'
  get 'newtownsquare', to: 'newtownsquare#main'
  get 'newtownsquare/partners'
  get 'norfolk', to: 'norfolk#main'
  get 'norfolk/partners'
  get 'northbethesda', to: 'northbethesda#main'
  get 'northbethesda/partners'
  get 'northkingstown', to: 'northkingstown#main'
  get 'northkingstown/partners'
  get 'norwalk', to: 'norwalk#main'
  get 'norwalk/partners'
  get 'norwell', to: 'norwell#main'
  get 'norwell/partners'
  get 'oakland', to: 'oakland#main'
  get 'oakland/partners'
  get 'oakton', to: 'oakton#main'
  get 'oakton/partners'
  get 'olney', to: 'olney#main'
  get 'olney/partners'
  get 'portchester', to: 'portchester#main'
  get 'portchester/partners'
  get 'potomac', to: 'potomac#main'
  get 'potomac/partners'
  get 'ramsey', to: 'ramsey#main'
  get 'ramsey/partners'
  get 'randolph', to: 'randolph#main'
  get 'randolph/partners'
  get 'redland', to: 'redland#main'
  get 'redland/partners'
  get 'reston', to: 'reston#main'
  get 'reston/partners'
  get 'ridgewood', to: 'ridgewood#main'
  get 'ridgewood/partners'
  get 'rockville', to: 'rockville#main'
  get 'rockville/partners'
  get 'rye', to: 'rye#main'
  get 'rye/partners'
  get 'ryebrook', to: 'ryebrook#main'
  get 'ryebrook/partners'
  get 'saddleriver', to: 'saddleriver#main'
  get 'saddleriver/partners'
  get 'sharon', to: 'sharon#main'
  get 'sharon/partners'
  get 'scarsdale', to: 'scarsdale#main'
  get 'scarsdale/partners'
  get 'scituate', to: 'scituate#main'
  get 'scituate/partners'
  get 'scotchplains', to: 'scotchplains#main'
  get 'scotchplains/partners'
  get 'sherborn', to: 'sherborn#main'
  get 'sherborn/partners'
  get 'shorthills', to: 'shorthills#main'
  get 'shorthills/partners'
  get 'sleepyhollow', to: 'sleepyhollow#main'
  get 'sleepyhollow/partners'
  get 'soma', to: 'soma#main'
  get 'soma/partners'
  get 'sterling', to: 'sterling#main'
  get 'sterling/partners'
  get 'sterlingridge', to: 'sterlingridge#main'
  get 'sterlingridge/partners'
  # get 'stratford', to: 'stratford#main'
  # get 'stratford/partners'
  get 'stoneham', to: 'stoneham#main'
  get 'stoneham/partners'
  get 'sudbury', to: 'sudbury#main'
  get 'sudbury/partners'
  get 'summit', to: 'summit#main'
  get 'summit/partners'
  get 'tarrytown', to: 'tarrytown#main'
  get 'tarrytown/partners'
  get 'tenafly', to: 'tenafly#main'
  get 'tenafly/partners'
  get 'travilah', to: 'travilah#main'
  get 'travilah/partners'
  get 'verona', to: 'verona#main'
  get 'verona/partners'
  get 'vienna', to: 'vienna#main'
  get 'vienna/partners'
  get 'villanova', to: 'villanova#main'
  get 'villanova/partners'
  get 'warren', to: 'warren#main'
  get 'warren/partners'
  get 'watchung', to: 'watchung#main'
  get 'watchung/partners'
  get 'wayland', to: 'wayland#main'
  get 'wayland/partners'
  get 'wayne', to: 'wayne#main'
  get 'wayne/partners'
  get 'wellesley', to: 'wellesley#main'
  get 'wellesley/partners'
  get 'westgreenwich', to: 'westgreenwich#main'
  get 'westgreenwich/partners'
  get 'weston', to: 'weston#main'
  get 'weston/partners'
  get 'westorange', to: 'westorange#main'
  get 'westorange/partners'
  get 'westport', to: 'westport#main'
  get 'westport/partners'
  get 'westfield', to: 'westfield#main'
  get 'westfield/partners'
  get 'westwood', to: 'westwood#main'
  get 'westwood/partners'
  get 'winchester', to: 'winchester#main'
  get 'winchester/partners'
  get 'winchesterma', to: 'winchesterma#main'
  get 'winchesterma/partners'
  get 'wolftrap', to: 'wolftrap#main'
  get 'wolftrap/partners'
  get 'woodclifflake', to: 'woodclifflake#main'
  get 'woodclifflake/partners'
  get 'wyckoff', to: 'wyckoff#main'
  get 'wyckoff/partners'
#
  get 'home/main'
  # get 'home/partners'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#main'
end
