Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      get 'ordheads/api'
      resources :ordheads
    end
  end

  get 'routetote', to: 'routetote#main'
  get 'tote', to: 'tote#main'
#   get 'alpine', to: 'alpine#main'
#   get 'alpine/partners'
  get 'barrington', to: 'barrington#main'
  get 'barrington/partners'
  get 'baskingridge', to: 'baskingridge#main'
  get 'baskingridge/partners'
  get 'bayberry', to: 'bayberry#main'
  get 'bayberry/partners'
  get 'bedford', to: 'bedford#main'
  get 'bedford/partners'
  get 'beechmontwoods', to: 'beechmontwoods#main'
  get 'beechmontwoods/partners'
#   get 'berkleyheights', to: 'berkleyheights#main'
#   get 'berkleyheights/partners'
#   get 'bernardville', to: 'bernardville#main'
#   get 'bernardville/partners'
  get 'berwyn', to: 'berwyn#main'
  get 'berwyn/partners'
#   get 'bethesda', to: 'bethesda#main'
#   get 'bethesda/partners'
#   get 'bloomfield', to: 'bloomfield#main'
#   get 'bloomfield/partners'
  get 'bronxville', to: 'bronxville#main'
  get 'bronxville/partners'
  get 'boontontownship', to: 'boontontownship#main'
  get 'boontontownship/partners'
#   get 'brookeville', to: 'brookeville#main'
#   get 'brookeville/partners'
  get 'brynmawr', to: 'brynmawr#main'
  get 'brynmawr/partners'
  get 'caldwell', to: 'caldwell#main'
  get 'caldwell/partners'
#   get 'canton', to: 'canton#main'
#   get 'canton/partners'
  get 'cedargrove', to: 'cedargrove#main'
  get 'cedargrove/partners'
#   get 'chatham', to: 'chatham#main'
#   get 'chatham/partners'
#   get 'chevychase', to: 'chevychase#main'
#   get 'chevychase/partners'
  get 'clarksville', to: 'clarksville#main'
  get 'clarksville/partners'
#   get 'closter', to: 'closter#main'
#   get 'closter/partners'
  get 'cohasset', to: 'cohasset#main'
  get 'cohasset/partners'
  get 'columbia', to: 'columbia#main'
  get 'columbia/partners'
  get 'concord', to: 'concord#main'
  get 'concord/partners'
#   get 'cranford', to: 'cranford#main'
#   get 'cranford/partners'
#   get 'creskill', to: 'creskill#main'
#   get 'creskill/partners'
  get 'darien', to: 'darien#main'
  get 'darien/partners'
#   get 'darnestown', to: 'darnestown#main'
#   get 'darnestown/partners'
#   get 'dennville', to: 'dennville#main'
#   get 'dennville/partners'
  get 'dobbsferry', to: 'dobbsferry#main'
  get 'dobbsferry/partners'
  get 'dover', to: 'dover#main'
  get 'dover/partners'
  get 'eastgreenwich', to: 'eastgreenwich#main'
  get 'eastgreenwich/partners'
  get 'elmsford', to: 'elmsford#main'
  get 'elmsford/partners'
  get 'englewood', to: 'englewood#main'
  get 'englewood/partners'
#   get 'essexfells', to: 'essexfells#main'
#   get 'essexfells/partners'
  get 'fallschurch', to: 'fallschurch#main'
  get 'fallschurch/partners'
  get 'fairfax', to: 'fairfax#main'
  get 'fairfax/partners'
#   get 'farhills', to: 'farhills#main'
#   get 'farhills/partners'
#   get 'franklinlakes', to: 'franklinlakes#main'
#   get 'franklinlakes/partners'
  get 'glenrock', to: 'glenrock#main'
  get 'glenrock/partners'
  get 'greatfalls', to: 'greatfalls#main'
  get 'greatfalls/partners'
  get 'greenwich', to: 'greenwich#main'
  get 'greenwich/partners'
#   get 'hardingtownship', to: 'hardingtownship#main'
#   get 'hardingtownship/partners'
  get 'hastingsonhudson', to: 'hastingsonhudson#main'
  get 'hastingsonhudson/partners'
  get 'haverford', to: 'haverford#main'
  get 'haverford/partners'
  get 'hillsdale', to: 'hillsdale#main'
  get 'hillsdale/partners'
  get 'hingham', to: 'hingham#main'
  get 'hingham/partners'
  get 'hohokus', to: 'hohokus#main'
  get 'hohokus/partners'
  get 'jamestown', to: 'jamestown#main'
  get 'jamestown/partners'
  get 'larchmont', to: 'larchmont#main'
  get 'larchmont/partners'
  get 'lexington', to: 'lexington#main'
  get 'lexington/partners'
  get 'lincoln', to: 'lincoln#main'
  get 'lincoln/partners'
#   get 'livingston', to: 'livingston#main'
#   get 'livingston/partners'
#   get 'longhilltwp', to: 'longhilltwp#main'
#   get 'longhilltwp/partners'
#   get 'madison', to: 'madison#main'
#   get 'madison/partners'
  get 'malden', to: 'malden#main'
  get 'malden/partners'
  get 'melrose', to: 'melrose#main'
  get 'melrose/partners'
  get 'medford', to: 'medford#main'
  get 'medford/partners'
#   get 'medway', to: 'medway#main'
#   get 'medway/partners'
  get 'montclair', to: 'montclair#main'
  get 'montclair/partners'
#   get 'mountainlake', to: 'mountainlake#main'
#   get 'mountainlake/partners'
#   get 'mountainside', to: 'mountainside#main'
#   get 'mountainside/partners'
#   get 'needham', to: 'needham#main'
#   get 'needham/partners'
  get 'newcanaan', to: 'newcanaan#main'
  get 'newcanaan/partners'
  get 'newport', to: 'newport#main'
  get 'newport/partners'
#   get 'newprovidence', to: 'newprovidence#main'
#   get 'newprovidence/partners'
  get 'newtownsquare', to: 'newtownsquare#main'
  get 'newtownsquare/partners'
#   get 'norfolk', to: 'norfolk#main'
#   get 'norfolk/partners'
  get 'northkingstown', to: 'northkingstown#main'
  get 'northkingstown/partners'
  get 'norwalk', to: 'norwalk#main'
  get 'norwalk/partners'
  get 'norwell', to: 'norwell#main'
  get 'norwell/partners'
  get 'oakton', to: 'oakton#main'
  get 'oakton/partners'
#   get 'olney', to: 'olney#main'
#   get 'olney/partners'
  get 'portchester', to: 'portchester#main'
  get 'portchester/partners'
#   get 'potomac', to: 'potomac#main'
#   get 'potomac/partners'
  get 'randolph', to: 'randolph#main'
  get 'randolph/partners'
#   get 'redland', to: 'redland#main'
#   get 'redland/partners'
  get 'reston', to: 'reston#main'
  get 'reston/partners'
  get 'ridgewood', to: 'ridgewood#main'
  get 'ridgewood/partners'
  get 'rye', to: 'rye#main'
  get 'rye/partners'
  get 'ryebrook', to: 'ryebrook#main'
  get 'ryebrook/partners'
  get 'saddleriver', to: 'saddleriver#main'
  get 'saddleriver/partners'
#   get 'sharon', to: 'sharon#main'
#   get 'sharon/partners'
  get 'scarsdale', to: 'scarsdale#main'
  get 'scarsdale/partners'
  get 'scituate', to: 'scituate#main'
  get 'scituate/partners'
#   get 'scotchplains', to: 'scotchplains#main'
#   get 'scotchplains/partners'
#   get 'sherborn', to: 'sherborn#main'
#   get 'sherborn/partners'
#   get 'shorthills', to: 'shorthills#main'
#   get 'shorthills/partners'
  get 'sleepyhollow', to: 'sleepyhollow#main'
  get 'sleepyhollow/partners'
  get 'soma', to: 'soma#main'
  get 'soma/partners'
  get 'sterling', to: 'sterling#main'
  get 'sterling/partners'
  get 'sterlingridge', to: 'sterlingridge#main'
  get 'sterlingridge/partners'
#   get 'stratford', to: 'stratford#main'
#   get 'stratford/partners'
#   get 'sudbury', to: 'sudbury#main'
#   get 'sudbury/partners'
#   get 'summit', to: 'summit#main'
#   get 'summit/partners'
  get 'tarrytown', to: 'tarrytown#main'
  get 'tarrytown/partners'
  get 'tenafly', to: 'tenafly#main'
  get 'tenafly/partners'
#   get 'travilah', to: 'travilah#main'
#   get 'travilah/partners'
  get 'verona', to: 'verona#main'
  get 'verona/partners'
  get 'vienna', to: 'vienna#main'
  get 'vienna/partners'
  get 'villanova', to: 'villanova#main'
  get 'villanova/partners'
  get 'watchung', to: 'watchung#main'
  get 'watchung/partners'
#   get 'wayland', to: 'wayland#main'
#   get 'wayland/partners'
  get 'wayne', to: 'wayne#main'
  get 'wayne/partners'
#   get 'wellesley', to: 'wellesley#main'
#   get 'wellesley/partners'
  get 'westgreenwich', to: 'westgreenwich#main'
  get 'westgreenwich/partners'
#   get 'weston', to: 'weston#main'
#   get 'weston/partners'
  get 'westorange', to: 'westorange#main'
  get 'westorange/partners'
  get 'westport', to: 'westport#main'
  get 'westport/partners'
  get 'westfield', to: 'westfield#main'
  get 'westfield/partners'
  get 'westwood', to: 'westwood#main'
  get 'westwood/partners'
  get 'winchester', to: 'winchester#main'
  get 'winchester/partners'
  get 'wolftrap', to: 'wolftrap#main'
  get 'wolftrap/partners'
  get 'woodclifflake', to: 'woodclifflake#main'
  get 'woodclifflake/partners'
#   get 'wyckoff', to: 'wyckoff#main'
#   get 'wyckoff/partners'
#
  get 'home/main'
  # get 'home/partners'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#main'
end
